### PR TITLE
likes and comments count issue fixed

### PR DESCRIPTION
**Pull request by ijameelkhan**

### CODE REVIEW

**Comment by ijameelkhan** [comment]
this fixes #199

**Comment by natan** [comment]
LGTM. I've encountered this issue as well. I'd like to see this merged and a new version published. Anything I can do to help?

**Comment by shyambhat** [comment]
Hi @ijameelkhan,
- Likes and comments count issue is fixed in v3.8.
- `followedByCount`,  `followsCount` and `mediaCount` are transient and not persisted to disk on purpose. The library encourages you to fetch it on each session to get its latest values.
- Would you care to explain your rationale behind making `accessToken` a property of `InstagramUser`?
Please resolve conflicts and resubmit a pull request if you think it needs to be included.
Thanks.

**Comment by ijameelkhan** [comment]
Yeah this is because i have a test case where user can login with multiple IG accounts and can switch between then instantly without asking for login again.

**Pull request closed without merging**
