### PR TITLE
Added search endpoint for locations near a coordinate

### PR DESCRIPTION
**Pull request by adamjuhasz**
location search endpoint added as requested in #15

### CODE REVIEW

**Comment by adamjuhasz** [comment]
Travis build fails because
/Users/travis/build/shyambhat/InstagramKit/InstagramKit/Engine/InstagramEngine.m:28:9: fatal error: 'InstagramLocation.h' file not found
#import "InstagramLocation.h"

Xcode finds it just fine in the models directory

**Comment by shyambhat** [comment]
Hey @adamjuhasz, it would be great if you could implement helpers for the other two endpoints ( https://instagram.com/developer/endpoints/locations/ ) for me to include this in the forthcoming pod version release this week. Thanks for the contribution. Cheers.

**Comment by adamjuhasz** [comment]
No worries, I'll get that out. Also trying to get Travis to not fail the repository

**Comment by adamjuhasz** [comment]
All endpoints added and tested

**Comment by shyambhat** [comment]
Thanks! Merged in `develop` branch.

**Pull request closed without merging**
