### PR TITLE
Added ability to get tagged users (into dev branch)

### PR DESCRIPTION
**Pull request by can16358p**
I needed the ability to get tagged users (as I've talked about here: https://github.com/shyambhat/InstagramKit/issues/124) and I've added such functionality.

Tagged users can be accessed like `media.usersInPhoto`.

Accessing their X/Y coordinates inside the photo is also supported.

### CODE REVIEW

**Comment by shyambhat** [comment]
Thanks @can16358p. There's some heavy documentation and refactoring work I did on the dev branch. Could you please fix conflicts and make your PR automatically mergable?

**Comment by can16358p** [comment]
Okay, laugh at me, but I'm not really good with this. Whatever I did I couldn't do it.

**Comment by shyambhat** [comment]
You need to pull from the dev branch, fix conflicts on your working branch and then resubmit the PR.

**Comment by RyanTLX** [comment]
Hey there @shyambhat, will the next release include this feature and any estimates on when will it be out?

**Comment by shyambhat** [comment]
@RyanTLX The PR is not mergable but I'll rewrite this and try to get it in by the end of this week.

**Pull request closed without merging**
