### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stefangeir**
After https://github.com/shyambhat/InstagramKit/commit/119c456df1e1cf203b959ab8e97cee0798775cf5 I got an error until setting the credentials in the `Pods/InstagramKit/Support Files/Info.plist`

### CODE REVIEW

**Comment by stefangeir** [comment]
This works if https://github.com/shyambhat/InstagramKit/commit/beac204cc1e9a8d6beade01c7de98f506dbddfa6 were reverted. That would also make InstagramKit be able to retrieve the info.plist during unit tests.

**Comment by shyambhat** [comment]
Can't place credentials in `Pods/InstagramKit/Support Files/Info.plist` as they'd be overwritten each time the pod is updated.

**Comment by stefangeir** [comment]
Oh of course okay.

It would also require reverting https://github.com/shyambhat/InstagramKit/commit/beac204cc1e9a8d6beade01c7de98f506dbddfa6 (just an observation, I know this shouldn't be merged.

When unit testing, is there any way to supress the 
`ERROR : InstagramKit - Invalid Client ID. Please set a valid value for the key "InstagramAppClientId" in the App's Info.plist file`
and
`ERROR : InstagramKit - Invalid Redirect URL. Please set a valid value for the key "InstagramAppRedirectURL" in the App's Info.plist file` warnings? (as the `[NSBundle mainBundle]` will just return an empty bundle with an empty `infoDictionary`)

**Comment by shyambhat** [comment]
Did you try placing the credentials also in the Pod project?
Yes, for running tests, we'll need to place the same credentials in two places. 
I can include a check for the environment, but that will only make the code look shabby

**Pull request closed without merging**
